name: webZio
on:
  push:
    branches:
      - master
    paths:
      - chpp/**
      - project/**
      - scala-common/**
      - sqlBuilder/**
      - web-zio/**
      - build.*
      - Dockerfile_webZio
jobs:
  build-web-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile_webZio
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/blackmorse/hat-all-stats/webzio:latest

